<?php
session_start();

if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header('Location: login.php');
    exit();
}

// Timezone list for the dropdown
$timezones = [
    'Asia/Manila', 'Asia/Singapore', 'Asia/Hong_Kong', 'Asia/Tokyo', 'Asia/Seoul', 'Asia/Bangkok', 'Asia/Dubai',
    'UTC', 'GMT',
    'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles',
    'Europe/London', 'Europe/Paris', 'Europe/Berlin',
];

$message = '';
$config_exists = file_exists('config.php');

// Load existing values if config.php exists
$defaults = [
    'location_name' => 'Burauen, Leyte',
    'lat' => '10.9',
    'lon' => '124.8',
    'cache_ttl' => '1800',
    'pirate_api_key' => '',
    'user_agent' => 'weatherapp@example.com',
    'timezone' => 'Asia/Manila'
];

if ($config_exists) {
    require_once 'config.php';
    $defaults = [
        'location_name' => defined('LOCATION_NAME') ? LOCATION_NAME : '',
        'lat' => defined('LATITUDE') ? LATITUDE : '10.9',
        'lon' => defined('LONGITUDE') ? LONGITUDE : '124.8',
        'cache_ttl' => defined('CACHE_TTL') ? CACHE_TTL : '1800',
        'pirate_api_key' => defined('PIRATE_API_KEY') ? PIRATE_API_KEY : '',
        'user_agent' => defined('USER_AGENT') ? USER_AGENT : '',
        'timezone' => defined('TIMEZONE') ? TIMEZONE : 'Asia/Manila'
    ];
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $location_name = htmlspecialchars($_POST['location_name']);
    $lat = htmlspecialchars($_POST['lat']);
    $lon = htmlspecialchars($_POST['lon']);
    $cache_ttl = htmlspecialchars($_POST['cache_ttl']);
    $pirate_api_key = htmlspecialchars($_POST['pirate_api_key']);
    $user_agent = htmlspecialchars($_POST['user_agent']);
    $timezone = htmlspecialchars($_POST['timezone']);

    $config_content = "<?php\n\n";
    $config_content .= "// Weather App Configuration\n// Generated by new_records.php\n\n";
    $config_content .= "define('LOCATION_NAME', '{$location_name}');\n";
    $config_content .= "define('LATITUDE', " . (!empty($lat) ? $lat : 10.9) . ");\n";
    $config_content .= "define('LONGITUDE', " . (!empty($lon) ? $lon : 124.8) . ");\n";
    $config_content .= "define('CACHE_TTL', " . (!empty($cache_ttl) ? $cache_ttl : 1800) . ");\n";
    $config_content .= "define('PIRATE_API_KEY', '{$pirate_api_key}');\n";
    $config_content .= "define('USER_AGENT', '{$user_agent}');\n";
    $config_content .= "define('TIMEZONE', '{$timezone}');\n";

    if (file_put_contents('config.php', $config_content)) {
        $message = '<div class="success">config.php created successfully! You can now return to the main page</a>.</div>';
        // Refresh defaults after saving
        $defaults = [
            'location_name' => $location_name, 'lat' => $lat, 'lon' => $lon,
            'cache_ttl' => $cache_ttl, 'pirate_api_key' => $pirate_api_key,
            'user_agent' => $user_agent, 'timezone' => $timezone
        ];
    } else {
        $message = '<div class="error">Error creating config.php. Check file permissions.</div>';
    }
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Weather App Configuration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="styles.css">
    <style>
        .note { font-size: 0.9em; color: #ddd; margin-top:-5px; margin-bottom:10px; }
    </style>
</head>
<body>
    <div class="container">
        <a href="add_credentials.php" style="float: left;">Manage Users</a>
        <a href="list_feedback.php" style="margin-left: 10px; float: left;">View Feedback</a>
        <a href="logout.php" style="float: right;">Logout</a>
        <h1>Weather App Setup</h1>
        <p>This page creates the <code>config.php</code> file used by the weather apps. Fill in the details below and click the button.</p>
        <?php if ($config_exists) echo '<div class="info">An existing config.php was found and its values have been loaded. Saving will overwrite it.</div>'; ?>
        <?php echo $message; ?>
        <form method="POST" action="">
            <label for="location_name">Location Name</label>
            <input type="text" id="location_name" name="location_name" placeholder="e.g., Burauen, Leyte" value="<?php echo htmlspecialchars($defaults['location_name']); ?>" required>

            <label for="lat">Latitude</label>
            <input type="text" id="lat" name="lat" placeholder="Default: 10.9" value="<?php echo htmlspecialchars($defaults['lat']); ?>">

            <label for="lon">Longitude</label>
            <input type="text" id="lon" name="lon" placeholder="Default: 124.8" value="<?php echo htmlspecialchars($defaults['lon']); ?>">

            <label for="cache_ttl">Cache TTL (seconds)</label>
            <input type="text" id="cache_ttl" name="cache_ttl" placeholder="Default: 1800" value="<?php echo htmlspecialchars($defaults['cache_ttl']); ?>">

            <label for="pirate_api_key">Pirate Weather API Key</label>
            <input type="text" id="pirate_api_key" name="pirate_api_key" value="<?php echo htmlspecialchars($defaults['pirate_api_key']); ?>">
            <p class="note">If left blank, the Pirate Weather app will not work.</p>

            <label for="user_agent">User-Agent (Valid Email for MET API)</label>
            <input type="text" id="user_agent" name="user_agent" placeholder="e.g., yourname@example.com" value="<?php echo htmlspecialchars($defaults['user_agent']); ?>" required>

            <label for="timezone">Timezone</label>
            <select id="timezone" name="timezone">
                <?php foreach ($timezones as $tz): ?>
                    <option value="<?php echo $tz; ?>" <?php echo ($tz === $defaults['timezone'] ? 'selected' : ''); ?>><?php echo $tz; ?></option>
                <?php endforeach; ?>
            </select>

            <input type="submit" value="Create / Update config.php">
        </form>
    </div>
</body>
</html>